# Generated by Django 4.2.14 on 2024-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('answer_a', models.CharField(max_length=100)),
                ('answer_b', models.CharField(max_length=100)),
                ('answer_c', models.CharField(max_length=100)),
                ('answer_d', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('impossible', 'Impossible')], default='easy', max_length=100)),
                ('image', models.FileField(blank=True, upload_to='project_images/')),
            ],
        ),
    ]
