# Generated by Django 4.2.14 on 2024-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(choices=[('answer_a', 'A'), ('answer_b', 'B'), ('answer_c', 'C'), ('answer_d', 'D')], default='answer_a', max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
