# Generated by Django 4.2.14 on 2024-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milioapp', '0002_questions_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
    ]
