# Generated by Django 4.2.14 on 2024-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milioapp', '0003_rename_questions_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('esport ', 'Esport'), ('game', 'Game'), ('lore', 'Lore')], default='game', max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
