# Generated by Django 4.2.15 on 2024-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milioapp', '0005_friendanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('esport', 'Esport'), ('game', 'Game'), ('lore', 'Lore')], default='game', max_length=100, null='false'),
        ),
    ]
